### ISSUE TITLE
DF on darwin doesn't support listing like this

### ISSUE THREAD

**Issue by KingsleyWeb** [bnikolic/recipe#1]
https://github.com/bnikolic/recipe/blob/fb631b3a019fe9c277cafb8582a6cc5be1842c4d/recipe/repo.py#L39

could be an el6 issue

**Comment by bnikolic** [comment]
Thanks for reporting. I tried on CSD3 and works so indeed likely el6
issue. Not sure worth fixing for darwin at this late stage?

On Fri, Dec 22, 2017, at 1:55 PM, Kingsley Gale-Sides wrote:
> https://github.com/bnikolic/recipe/blob/fb631b3a019fe9c277cafb8582a6cc5be1842c4d/recipe/repo.py#L39> could be an el6 issue


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/bnikolic/recipe/issues/1

**Comment by KingsleyWeb** [comment]
I agree, probably not worthwhile, el7 is the way forwards anyway

**Comment by bnikolic** [comment]
Allright, cosing without a fix/workaround
